### ISSUE TITLE
Harbinger Skyriss

### ISSUE THREAD

**Issue by Arrakoan** [korakion/Shadowsong#174] opened 2016-09-24 19:27 UTC
Harbinger skyriss (The final boss in the arcatraz) spawns clones of himself with lower hp (around 17k) which should be killable. Unlike normally, targetting them and trying to attack them with skills is not possible and a message will pop up saying ''Invalid Target'' as a GM in GM mode. Normal players doing this dungeon are not able to target them at all.

Arcatraz 5man normal mode.)

**Comment by Lucilla-Korakion** [comment] 2016-09-24 19:43
Duplicate of issue #173 so closing this off.

**Closed as completed by Lucilla-Korakion** 2016-09-24 19:43 UTC
Labels: duplicate
