### ISSUE TITLE
Into The Scarlet Monastery quest

### ISSUE THREAD

**Issue by Mysterexpo** [korakion/Shadowsong#65] opened 2016-08-23 02:36 UTC
During this quest High Inquisitor Whitemane does not resurrect Scarlet Commander Morgrain and in doing so you are unable to complete this quest. In fact his body stays put or just follows you around the instance.

**Comment by Jackedcow** [comment] 2016-09-04 18:43
She will cancel the Rez cast halfway thru to cast smite.

**Comment by Lucilla-Korakion** [comment] 2016-10-06 18:16
Closing as duplicate of #206

**Closed as completed by Lucilla-Korakion** 2016-10-06 18:16 UTC
Labels: duplicate
