### ISSUE TITLE
Quest Bugged Disrupt the Greengill Coast

### ISSUE THREAD

**Issue by Qoue705** [korakion/Shadowsong#167] opened 2016-09-23 03:05 UTC
The daily quest requires killing casters that drop orbs of murloc control. When I used the orb on the murlocs they do not react( break free and attack the nearest naga) but they aren't.

**Comment by Lucilla-Korakion** [comment] 2016-09-25 11:46
Not able to replicate issue - can complete quest as intended.

Item works and does give credit when used see below:

![murlocs](https://cloud.githubusercontent.com/assets/22416538/18815086/c3a73586-831d-11e6-82c5-a27b68a5e1ef.PNG)

**Please note that if the Murlocs appear RED in color, it is because they have already had the item used on them recently (perhaps by another player) and you will receive no credit for this.**

No bug here so closing this off.

Regards.
Lucilla

**Closed as completed by Lucilla-Korakion** 2016-09-25 11:46 UTC
Labels: False
