### ISSUE TITLE
Docks = not considered outdoors?

### ISSUE THREAD

**Issue by salamort** [korakion/Shadowsong#165] opened 2016-09-22 21:04 UTC
This is bothering me as it is not retail like and therefore is categorized as a bug in my opinion.

Docks in Menethil and STV (bootybay), are not considered outdoors even tho they are outdoors..,therefore you cannot mount up to catch a boat for example.

**Comment by ghost** [comment] 2016-09-23 12:14
Hi Salamort,

Mounts were not able to be used in docks in TBC - this change was made in WOTLK, therefore this is not a bug just a 'nice to have'

https://www.engadget.com/2008/08/12/mounts-now-welcome-in-booty-bay

Regards,
Hassel

**Comment by salamort** [comment] 2016-09-23 12:46
Hello Hassel,

Forgive me for my lack of research. I got confused with my expansions. Thank you for the link!

Salamort (Dew)

**Comment by Lucilla-Korakion** [comment] 2016-09-24 17:10
Closing issue as per above.

**Closed as completed by Lucilla-Korakion** 2016-09-24 17:10 UTC
Labels: False
